import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Addproperty</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryesillimportunavailabledatesfromanotherwebsite">
            PricingandcalendarYesIllimportunavailabledatesfromanotherwebsite
          </Link>
        </li>
        <li>
          <Link to="/propertydetailslivingroom">PropertyDetailsLivingRoom</Link>
        </li>
        <li>
          <Link to="/parkingpaid">Parkingpaid</Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetailsy">
            PropertySetupBreakfastDetailsy
          </Link>
        </li>
        <li>
          <Link to="/grouphomepage">Grouphomepage</Link>
        </li>
        <li>
          <Link to="/propertycategorypage">Propertycategorypage</Link>
        </li>
        <li>
          <Link to="/howmuchpropertytolist">Howmuchpropertytolist</Link>
        </li>
        <li>
          <Link to="/confirmation">Confirmation</Link>
        </li>
        <li>
          <Link to="/questionaboutproperty">Questionaboutproperty</Link>
        </li>
        <li>
          <Link to="/namelocation1stpage">NameLocation1stPage</Link>
        </li>
        <li>
          <Link to="/namelocation2ndpage">NameLocation2ndPage</Link>
        </li>
        <li>
          <Link to="/namelocation3rdpage">NameLocation3rdPage</Link>
        </li>
        <li>
          <Link to="/propertysetuppropertydetails">
            PropertySetupPropertyDetails
          </Link>
        </li>
        <li>
          <Link to="/propertysetupamenities">PropertySetupAmenities</Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetails">
            PropertySetupBreakfastDetails
          </Link>
        </li>
        <li>
          <Link to="/language">Language</Link>
        </li>
        <li>
          <Link to="/rules">Rules</Link>
        </li>
        <li>
          <Link to="/hostprofile">Hostprofile</Link>
        </li>
        <li>
          <Link to="/photosimportphotos">PhotosImportPhotos</Link>
        </li>
        <li>
          <Link to="/photosimportphotosairbnb">PhotosImportPhotosAirbnb</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarno">PricingandcalendarNo</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryes">PricingandcalendarYes</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryestwo">PricingandcalendarYesTwo</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarpricepernight">
            PricingandcalendarPricepernight
          </Link>
        </li>
        <li>
          <Link to="/pricingandcalendarrateplans">
            PricingandcalendarRateplans
          </Link>
        </li>
        <li>
          <Link to="/parking">Parking</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarfive">PricingandcalendarFive</Link>
        </li>
        <li>
          <Link to="/pricingandcalendaryesillconnectwithachannelmanager">
            PricingandcalendarYesIllconnectwithachannelmanager
          </Link>
        </li>
        <li>
          <Link to="/propertydetailsotherspaces">
            PropertyDetailsOtherSpaces
          </Link>
        </li>
        <li>
          <Link to="/propertysetupbreakfastdetailsn">
            PropertySetupBreakfastDetailsn
          </Link>
        </li>
        <li>
          <Link to="/parkingfree">Parkingfree</Link>
        </li>
        <li>
          <Link to="/propertydetailsbedroomtwo">PropertyDetailsBedroomTwo</Link>
        </li>
        <li>
          <Link to="/pricingandcalendarnoiwontsyncmyavailability">
            PricingandcalendarNoIwontsyncmyavailability
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
